version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: test-frontend-app
    restart: unless-stopped

networks:
  default:
    driver: bridge
