name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 构建应用
      run: npm run build
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 构建 Docker 镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: test-frontend-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: 测试 Docker 镜像
      run: |
        docker run -d -p 8080:80 --name test-container test-frontend-app:latest
        sleep 5
        curl -f http://localhost:8080 || exit 1
        docker stop test-container
